"""Property-based accounting invariants (SPEC_FINAL-1.2.md §13).

Random fixtures are generated by hypothesis and pushed through BOTH
independent implementations. The strongest property is the randomized
differential itself: sim and reference ledger must reconcile on every
generated fixture, not just the curated ones.
"""
import pytest
from hypothesis import given, settings, strategies as st

from lab import protocol as P
from lab.verify.differential import compare, run_sim

B15 = P.BAR_15M_MS
T0 = 1_700_000_000_000 - (1_700_000_000_000 % P.BAR_4H_MS)
LIM = {"max_positions": 6, "max_gross_exposure": 1.5, "min_notional": 50.0}
COSTS = [{"hs": 0.0, "slip": 0.0, "fee": 0.0},
         {"hs": 0.001, "slip": 0.0005, "fee": 0.0005},
         {"hs": 0.00025, "slip": 0.00035, "fee": 0.0005}]


@st.composite
def fixtures(draw):
    n_sym = draw(st.integers(1, 3))
    n_bars = draw(st.integers(8, 32))
    symbols = [f"S{i}" for i in range(n_sym)]
    bars = {}
    for si, s in enumerate(symbols):
        px = 50.0 * (si + 1)
        rows = []
        for i in range(n_bars):
            if draw(st.integers(0, 9)) == 0:      # ~10% missing bars
                continue
            r = draw(st.floats(-0.04, 0.04))
            o = px
            c = px * (1 + r)
            h = max(o, c) * (1 + draw(st.floats(0, 0.01)))
            l = min(o, c) * (1 - draw(st.floats(0, 0.01)))
            rows.append([T0 + i * B15, o, h, l, c])
            px = c
        if rows:
            bars[s] = rows
    if not bars:
        bars = {"S0": [[T0, 100, 100.1, 99.9, 100]]}
        symbols = ["S0"]

    ins = []
    n_entries = draw(st.integers(1, 6))
    for _ in range(n_entries):
        t = T0 + draw(st.integers(0, n_bars - 1)) * B15
        s = draw(st.sampled_from(symbols))
        px = 50.0 * (symbols.index(s) + 1)
        ins.append({"t": t, "type": "entry", "symbol": s,
                    "side": draw(st.sampled_from([1, -1])),
                    "qty": draw(st.floats(0.5, 80)),
                    "costs": draw(st.sampled_from(COSTS)),
                    "stop_offset": px * draw(st.floats(0.01, 0.15)),
                    "target_offset": px * draw(st.floats(0.01, 0.2)),
                    "max_notional": draw(st.sampled_from(
                        [None, 1000.0, 3000.0]))})
    for pid in range(1, draw(st.integers(1, 4))):
        ins.append({"t": T0 + draw(st.integers(1, n_bars - 1)) * B15,
                    "type": "exit", "pos_id": pid, "reason": "manual",
                    "slip_mult": 1.0})
    ins.sort(key=lambda x: x["t"])

    funding = {}
    if draw(st.booleans()):
        for s in symbols:
            f = {}
            for i in range(n_bars):
                t = T0 + i * B15
                if t % P.FUNDING_INTERVAL_MS == 0 and draw(st.booleans()):
                    f[t] = draw(st.floats(-0.001, 0.001))
            if f:
                funding[s] = f

    return {"starting_cash": draw(st.sampled_from([2_000.0, 10_000.0])),
            "limits": LIM, "instructions": ins, "bars": bars,
            "funding": funding,
            "funding_interval_ms": P.FUNDING_INTERVAL_MS, "bar_ms": B15}


@settings(max_examples=60, deadline=None)
@given(fixtures())
def test_random_differential_and_invariants(fx):
    # 1) THE differential property: both implementations reconcile
    rep = compare(fx)
    assert rep["match"], rep

    events, cash = run_sim(fx)

    # 2) identical deterministic inputs -> identical ledgers
    events2, cash2 = run_sim(fx)
    assert events == events2 and cash == cash2

    # 3) accounting identity: cash = start - open fees + sum(pnl - fee)
    #    at closes - funding paid  (fees can therefore never increase equity)
    delta = 0.0
    for ev in events:
        if ev["kind"] == "fill_open":
            assert ev["fee"] >= 0
            delta -= ev["fee"]
        elif ev["kind"] == "fill_close":
            assert ev["fee"] >= 0
            assert ev["qty"] >= 0 and ev["remaining_qty"] >= -1e-12
            delta += ev["pnl"] - ev["fee"]
        elif ev["kind"] == "funding":
            delta -= ev["paid"]
    assert cash == pytest.approx(fx["starting_cash"] + delta, rel=1e-9, abs=1e-6)

    # 4) insolvent accounts never open new risk
    ruined_at = next((i for i, ev in enumerate(events)
                      if ev["kind"] == "insolvency"), None)
    if ruined_at is not None:
        assert not any(ev["kind"] == "fill_open"
                       for ev in events[ruined_at:])

    # 5) rejections and drops never change cash (reference ledger records
    #    cash_after on every row)
    from lab.refledger.ledger import replay
    ledger = replay(fx)
    prev_cash = fx["starting_cash"]
    for row in ledger:
        if row["kind"] in ("reject", "cancel", "exit_dropped",
                           "exit_deferred", "protection_deferred",
                           "funding_missing", "ambiguity",
                           "gap_stop_priority"):
            assert row["cash_after"] == prev_cash
        prev_cash = row["cash_after"]


@settings(max_examples=25, deadline=None)
@given(st.lists(st.floats(-1.5, 1.5), min_size=4, max_size=20),
       st.floats(1, 8), st.floats(1, 12), st.floats(0.5, 5))
def test_long_short_symmetry_property(steps, stop_off, tgt_off, qty):
    """Mirrored additive prices + flipped side + identical costs => identical
    cash outcome (cost-free, no caps binding, no funding)."""
    k = 100.0
    lim = {"max_positions": 10, "max_gross_exposure": 100.0,
           "min_notional": 0.0}
    lv = k
    rows, mrows = [], []
    for i, dp in enumerate(steps):
        o = lv
        c = lv + dp
        h = max(o, c) + 0.05
        l = min(o, c) - 0.05
        rows.append([T0 + i * B15, o, h, l, c])
        mrows.append([T0 + i * B15, 2 * k - o, 2 * k - l, 2 * k - h,
                      2 * k - c])
        lv = c
    c0 = {"hs": 0.0, "slip": 0.0, "fee": 0.0}

    def make(bars, side):
        return {"starting_cash": 100_000.0, "limits": lim,
                "instructions": [
                    {"t": T0, "type": "entry", "symbol": "A", "side": side,
                     "qty": qty, "costs": c0, "stop_offset": stop_off,
                     "target_offset": tgt_off, "max_notional": None},
                    {"t": T0 + (len(steps) - 1) * B15, "type": "exit",
                     "pos_id": 1, "reason": "manual", "slip_mult": 1.0}],
                "bars": {"A": bars}, "funding": {},
                "funding_interval_ms": P.FUNDING_INTERVAL_MS, "bar_ms": B15}

    _, cash_long = run_sim(make(rows, +1))
    _, cash_short = run_sim(make(mrows, -1))
    assert cash_long == pytest.approx(cash_short, rel=1e-9, abs=1e-6)
